# Generated by Django 5.1.6 on 2026-04-25 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_refactor_for_multi_items_and_lookups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE orders_order DROP COLUMN IF EXISTS created_by_id;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='order',
                    name='created_by',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE orders_order DROP COLUMN IF EXISTS entry_time;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='order',
                    name='entry_time',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE orders_order ADD COLUMN IF NOT EXISTS quantity integer NOT NULL DEFAULT 1;',
                    reverse_sql='ALTER TABLE orders_order DROP COLUMN IF EXISTS quantity;',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='quantity',
                    field=models.PositiveIntegerField(default=1),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='customer_status',
                    field=models.ForeignKey(blank=True, db_column='customer_status_master_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customerstatus'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='delivered_reference',
                    field=models.CharField(blank=True, db_column='old_previous_reference', max_length=120, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='payment_medium',
                    field=models.ForeignKey(blank=True, db_column='payment_medium_master_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.paymentmedium'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='payment_method',
                    field=models.ForeignKey(blank=True, db_column='payment_method_master_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.paymentmethod'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='platform_type',
                    field=models.ForeignKey(blank=True, db_column='platform_type_master_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.platformtype'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='reference_number',
                    field=models.CharField(db_column='old_reference_number', max_length=120),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='status',
                    field=models.ForeignKey(blank=True, db_column='status_master_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus'),
                ),
            ],
        ),
    ]
