# Generated by Django 5.1.6 on 2026-09-10 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fields', models.JSONField(default=dict)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('has_pending_server_review', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_data', models.TextField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=60)),
                ('local_read_status', models.CharField(choices=[('ok', 'OK'), ('unreadable', 'Unreadable')], default='ok', max_length=20)),
                ('server_status', models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='not_needed', max_length=20)),
                ('server_ocr_text', models.TextField(blank=True, default='')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='invoices.invoicerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
