# Generated by Django 5.1.6 on 2026-09-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerecord',
            name='record_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('mobile_money_receipt', 'Mobile Money Receipt')], default='invoice', max_length=30),
        ),
    ]
